cmake_minimum_required(VERSION 3.17)
project (MulticoreProject)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
add_executable(multicore_project new.cpp)
find_package (SQLite3)
if (SQLITE3_FOUND)
    include_directories(${SQLITE3_INCLUDE_DIRS})
    target_link_libraries (multicore_project ${SQLITE3_LIBRARIES})
endif (SQLITE3_FOUND)